/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import sop.webflow.rt.api.BaseProcessClass;
import com.ecquaria.cloud.helper.EngineHelper;

public class INTERNET___IncidentFollowUPReport1B___1 extends BaseProcessClass {

	private static final String DELEGATOR ="followUPReportDelegator";

	public void start_OnStepProcess_0() throws Exception {
	// 		Start->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "startFollowup1B", this);
	}

	public void preReferenceNo_OnStepProcess_0() throws Exception {
	// 		PreReferenceNo->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "preReferenceNo", this);
	}

	public void handleReferenceNo_OnStepProcess_0() throws Exception {
		// 		HandleReferenceNo->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "handleReferenceNo1B", this);
	}

	public void preFollowUPReport1B_OnStepProcess_0() throws Exception {
	// 		PreFollowUPReport1B->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "preFollowUPReport1B", this);
	}

	public void handleFollowUPReport1B_OnStepProcess_0() throws Exception {
	// 		HandleFollowUPReport1B->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "handleFollowUPReport1B", this);
	}

	public void preViewReport1B_OnStepProcess_0() throws Exception {
	// 		PreViewReport1B->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "preViewReport1B", this);
	}

	public void submitReport1B_OnStepProcess_0() throws Exception {
	// 		SubmitReport1B->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "submitReport1B", this);
	}

}
