/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;
import sop.webflow.rt.api.BaseProcessClass;

public class INTRANET___MohInspSupAddAvailability___1 extends BaseProcessClass {

	private static final long serialVersionUID = 9146624796403831929L;
	private static final String DELEGATOR ="inspSupAddAvailabilityDelegator";

	public void inspSupAddAvailabilityStart_OnStepProcess_0() throws Exception {
	// 		InspSupAddAvailabilityStart->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspSupAddAvailabilityStart", this);
	}

	public void inspSupAddAvailabilityInit_OnStepProcess_0() throws Exception {
	// 		InspSupAddAvailabilityInit->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspSupAddAvailabilityInit", this);
	}

	public void inspSupAddAvailabilityPre_OnStepProcess_0() throws Exception {
	// 		InspSupAddAvailabilityPre->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspSupAddAvailabilityPre", this);
	}

	public void inspSupAddAvailabilityStep_OnStepProcess_0() throws Exception {
	// 		InspSupAddAvailabilityStep->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspSupAddAvailabilityStep", this);
	}

	public void inspSupAddAvailabilitySearch_OnStepProcess_0() throws Exception {
	// 		InspSupAddAvailabilitySearch->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspSupAddAvailabilitySearch", this);
	}

	public void inspSupAddAvailabilitySort_OnStepProcess_0() throws Exception {
	// 		InspSupAddAvailabilitySort->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspSupAddAvailabilitySort", this);
	}

	public void inspSupAddAvailabilityPage_OnStepProcess_0() throws Exception {
	// 		InspSupAddAvailabilityPage->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspSupAddAvailabilityPage", this);
	}

	public void inspSupAddAvailabilityQuery_OnStepProcess_0() throws Exception {
	// 		InspSupAddAvailabilityQuery->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspSupAddAvailabilityQuery", this);
	}

	public void inspSupAddAvailabilityAdd_OnStepProcess_0() throws Exception {
	// 		InspSupAddAvailabilityAdd->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspSupAddAvailabilityAdd", this);
	}

	public void inspSupAddAvailabilityVali_OnStepProcess_0() throws Exception {
	// 		InspSupAddAvailabilityVali->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspSupAddAvailabilityVali", this);
	}

	public void inspSupAddAvailabilityConfirm_OnStepProcess_0() throws Exception {
	// 		InspSupAddAvailabilityConfirm->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspSupAddAvailabilityConfirm", this);
	}

	public void inspSupAddAvailabilityStep2_OnStepProcess_0() throws Exception {
	// 		InspSupAddAvailabilityStep2->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspSupAddAvailabilityStep2", this);
	}

	public void inspSupAddAvailabilityDelete_OnStepProcess_0() throws Exception {
	// 		InspSupAddAvailabilityDelete->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspSupAddAvailabilityDelete", this);
	}

}
