/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import sop.i18n.MultiLangUtil;
import sop.webflow.rt.api.BaseProcessClass;

public class EGPCLOUD___SetLanguage___1 extends BaseProcessClass {

	public void step2_OnStepProcess_0() throws Exception {
		String lang = request.getParameter("language");
		MultiLangUtil.setSiteLanguage(lang);
	// 		Step2->OnStepProcess
	}

}
