/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;

import sop.webflow.rt.api.BaseProcessClass;

public class INTRANET___MohKpiColourShow___1 extends BaseProcessClass {

	private static final long serialVersionUID = 5011082595486699149L;
	private static final String DELEGATOR ="kpiColourByWorkDaysBatchJob";

	public void mohKpiColourShowStart_OnStepProcess_0() throws Exception {
	// 		mohKpiColourShowStart->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "mohKpiColourShowStart", this);
	}

	public void mohKpiColourShowStep_OnStepProcess_0() throws Exception {
	// 		mohKpiColourShowStep->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "mohKpiColourShowStep", this);
	}

}
