/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;
import sop.webflow.rt.api.BaseProcessClass;

public class INTERNET___MohRenewalFacilityRegistration___1 extends BaseProcessClass {

	private static final String DELEGATOR ="renewalFacilityRegisterDelegator";
	
	public void start_OnStepProcess_0() throws Exception {
	// 		Start->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "start", this);
	}

	public void init_OnStepProcess_0() throws Exception {
	// 		Init->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "init", this);
	}

	public void preInstruction_OnStepProcess_0() throws Exception {
	// 		PreInstruction->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "preInstruction", this);
	}

	public void preReview_OnStepProcess_0() throws Exception {
	// 		PreReview->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "preReview", this);
	}

	public void preCompInfo_OnStepProcess_0() throws Exception {
	// 		PreCompInfo->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "preCompInfo", this);
	}

	public void preServiceSelection_OnStepProcess_0() throws Exception {
	// 		PreServiceSelection->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "preServiceSelection", this);
	}

	public void preFacProfile_OnStepProcess_0() throws Exception {
	// 		PreFacProfile->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "preFacProfile", this);
	}

	public void preFacOperator_OnStepProcess_0() throws Exception {
	// 		PreFacOperator->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "preFacOperator", this);
	}

	public void preFacInfoAuthoriser_OnStepProcess_0() throws Exception {
	// 		PreFacInfoAuthoriser->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "preFacInfoAuthoriser", this);
	}

	public void preFacAdmin_OnStepProcess_0() throws Exception {
	// 		PreFacAdmin->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "preFacAdmin", this);
	}

	public void preFacOfficer_OnStepProcess_0() throws Exception {
	// 		PreFacOfficer->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "preFacOfficer", this);
	}

	public void preFacInfoCommittee_OnStepProcess_0() throws Exception {
	// 		PreFacInfoCommittee->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "preFacInfoCommittee", this);
	}

	public void preBAToxin_OnStepProcess_0() throws Exception {
	// 		PreBAToxin->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "preBAToxin", this);
	}

	public void preOtherAppInfo_OnStepProcess_0() throws Exception {
	// 		PreOtherAppInfo->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "preOtherAppInfo", this);
	}

	public void prePrimaryDoc_OnStepProcess_0() throws Exception {
	// 		PrePrimaryDoc->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "prePrimaryDoc", this);
	}

	public void handleInstruction_OnStepProcess_0() throws Exception {
	// 		HandleInstruction->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "handleInstruction", this);
	}

	public void handleReview_OnStepProcess_0() throws Exception {
	// 		HandleReview->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "handleReview", this);
	}

	public void handleCompInfo_OnStepProcess_0() throws Exception {
	// 		HandleCompInfo->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "handleCompInfo", this);
	}

	public void handleServiceSelection_OnStepProcess_0() throws Exception {
	// 		HandleServiceSelection->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "handleServiceSelection", this);
	}

	public void handleFacProfile_OnStepProcess_0() throws Exception {
	// 		HandleFacProfile->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "handleFacProfile", this);
	}

	public void handleFacOperator_OnStepProcess_0() throws Exception {
	// 		HandleFacOperator->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "handleFacOperator", this);
	}

	public void handleFacInfoAuthoriser_OnStepProcess_0() throws Exception {
	// 		HandleFacInfoAuthoriser->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "handleFacInfoAuthoriser", this);
	}

	public void handleFacAdmin_OnStepProcess_0() throws Exception {
	// 		HandleFacAdmin->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "handleFacAdmin", this);
	}

	public void handleFacOfficer_OnStepProcess_0() throws Exception {
	// 		HandleFacOfficer->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "handleFacOfficer", this);
	}

	public void handleFacInfoCommittee_OnStepProcess_0() throws Exception {
	// 		HandleFacInfoCommittee->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "handleFacInfoCommittee", this);
	}

	public void handleBAToxin_OnStepProcess_0() throws Exception {
	// 		HandleBAToxin->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "handleBAToxin", this);
	}

	public void handleOtherAppInfo_OnStepProcess_0() throws Exception {
	// 		HandleOtherAppInfo->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "handleOtherAppInfo", this);
	}

	public void handlePrimaryDoc_OnStepProcess_0() throws Exception {
	// 		HandlePrimaryDoc->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "handlePrimaryDoc", this);
	}

	public void actionFilter_OnStepProcess_0() throws Exception {
	// 		ActionFilter->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "actionFilter", this);
	}

	public void jumpFilter_OnStepProcess_0() throws Exception {
	// 		JumpFilter->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "jumpFilter", this);
	}

	public void preAcknowledgement_OnStepProcess_0() throws Exception {
	// 		PreAcknowledgement->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "preAcknowledgement", this);
	}

}
