/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import sop.webflow.rt.api.BaseProcessClass;

public class INTRANET___DOProcessingIncidentFollowup1B___1 extends BaseProcessClass {

	public void start_OnStepProcess_0() throws Exception {
	// 		Start->OnStepProcess
	}

	public void init_OnStepProcess_0() throws Exception {
	// 		Init->OnStepProcess
	}

	public void preProcessingData_OnStepProcess_0() throws Exception {
	// 		PreProcessingData->OnStepProcess
	}

	public void handleProcessing_OnStepProcess_0() throws Exception {
	// 		HandleProcessing->OnStepProcess
	}

	public void actionFilter_OnStepProcess_0() throws Exception {
	// 		ActionFilter->OnStepProcess
	}

	public void submitProcessing_OnStepProcess_0() throws Exception {
	// 		SubmitProcessing->OnStepProcess
	}

}
