/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;

import sop.webflow.rt.api.BaseProcessClass;

public class INTRANET___MohFeUserManagement___1 extends BaseProcessClass {
	private static final String DELEGATOR ="feUserManagement";

	public void prepare_OnStepProcess_0() throws Exception {
	// 		prepare->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "prepare", this); 
	}

	public void search_OnStepProcess_0() throws Exception {
	// 		search->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "search", this); 
	}

	public void delete_OnStepProcess_0() throws Exception {
	// 		delete->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "delete", this); 
	}

	public void searchPage_OnStepProcess_0() throws Exception {
	// 		searchPage->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "searchPage", this); 
	}

	public void edit_OnStepProcess_0() throws Exception {
	// 		edit->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "edit", this); 
	}

	public void create_OnStepProcess_0() throws Exception {
	// 		create->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "create", this); 
	}

	public void validation_OnStepProcess_0() throws Exception {
	// 		validation->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "validation", this); 
	}

	public void start_OnStepProcess_1() throws Exception {
	// 		start->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "start", this); 
	}


}
