/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;
import sop.webflow.rt.api.BaseProcessClass;

public class INTRANET___MohInspectorProRectification___1 extends BaseProcessClass {
	
	private static final long serialVersionUID = 814913878876678650L;
	private static final String DELEGATOR ="inspectionRectificationProDelegator";

	public void inspectorProRectificationStart_OnStepProcess_0() throws Exception {
	// 		InspectorProRectificationStart->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspectorProRectificationStart", this);
	}

	public void inspectorProRectificationInit_OnStepProcess_0() throws Exception {
	// 		InspectorProRectificationInit->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspectorProRectificationInit", this);
	}

	public void inspectorProRectificationPre_OnStepProcess_0() throws Exception {
	// 		InspectorProRectificationPre->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspectorProRectificationPre", this);
	}

	public void inspectorProRectificationValid_OnStepProcess_0() throws Exception {
	// 		InspectorProRectificationValid->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspectorProRectificationValid", this);
	}

	public void inspectorProRectificationReq_OnStepProcess_0() throws Exception {
	// 		InspectorProRectificationReq->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspectorProRectificationReq", this);
	}

	public void inspectorProRectificationAcc_OnStepProcess_0() throws Exception {
	// 		InspectorProRectificationAcc->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspectorProRectificationAcc", this);
	}

	public void inspectorProRectificationAccCond_OnStepProcess_0() throws Exception {
	// 		InspectorProRectificationAccCond->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspectorProRectificationAccCond", this);
	}

}
