/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;

import sop.webflow.rt.api.BaseProcessClass;

public class INTERNET___MohInterInboxMenuControl___1 extends BaseProcessClass {

	private static final String DELEGATOR ="inboxMenuControlDelegator";
	public void step1_OnStepProcess_0() throws Exception {
	// 		Step1->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "doStart", this);
	}

	public void prepareJump_OnStepProcess_0() throws Exception {
	// 		prepareJump->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "prepareJump", this);
	}

	public void doJump_OnStepProcess_0() throws Exception {
	// 		doJump->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "doJump", this);
	}

}
