/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;
import sop.webflow.rt.api.BaseProcessClass;

public class INTERNET___MohRequestForChange___1 extends BaseProcessClass {
	private static final String DELEGATOR ="requestForChangeDelegator";


	public void prepare_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "prepare", this);
	}

	public void doChoose_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doChoose", this);
	}

	public void jump_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "jump", this);
	}

	public void step1_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doStart", this);
	}

	public void step2_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "compareChangePercentage", this);
	}

	public void doChooseInfo_OnStepProcess_0 () throws Exception { 
		// 		doChooseInfo->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "doFirstView", this);
	}

	public void prepareAmend_OnStepProcess_0 () throws Exception { 
		EngineHelper.delegate(DELEGATOR, "prepareFirstView", this);
	}

	public void step3_OnStepProcess_0() throws Exception {
	// 		Step3->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "doBack", this);
	}

	public void step2_OnStepProcess_1() throws Exception {
	// 		Step2->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "prepareTranfer", this);
	}

	public void prepareDraft_OnStepProcess_0() throws Exception {
	// 		prepareDraft->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "prepareDraft", this);
	}

	public void payment_OnStepProcess_0() throws Exception {
	// 		payment->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "submitPayment", this);
	}

}
