/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import sop.webflow.rt.api.BaseProcessClass;
import com.ecquaria.cloud.helper.EngineHelper;

public class INTERNET___MohInterInboxPersonnelList___1 extends BaseProcessClass {
	
	private static final String DELEGATOR ="inboxMenuDelegator";

	public void preparePersonnelList_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preparePersonnelList", this);
	}

	public void doPersonnelList_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doPersonnelList", this);
	}

	public void preparePersonnelEdit_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preparePersonnelEdit", this);
	}

	public void doPersonnelEdit_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doPersonnelEdit", this);
	}

	public void jump_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "jump", this);
	}

	
}
