/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import sop.webflow.rt.api.BaseProcessClass;
import com.ecquaria.cloud.helper.EngineHelper;

public class INTRANET___MohBsbIntraLogin___1 extends BaseProcessClass {
	private static final String DELEGATOR ="bsbBeLoginDelegator";


	public void start_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "start", this); 
	}

	public void initLogin_OnStepProcess_0 () throws Exception { 
		EngineHelper.delegate(DELEGATOR, "initLogin", this); 
	}

	public void preLogin_OnStepProcess_0 () throws Exception { 
		EngineHelper.delegate(DELEGATOR, "preLogin", this); 
	}

	public void aferSubmit_OnStepProcess_0 () throws Exception { 
		EngineHelper.delegate(DELEGATOR, "afterSubmit", this); 
	}

	public void doLogin_OnStepProcess_0 () throws Exception { 
		EngineHelper.delegate(DELEGATOR, "doLogin", this); 
	}

}
