/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import sop.webflow.rt.api.BaseProcessClass;
import com.ecquaria.cloud.helper.EngineHelper;

public class INTERNET___BsbReportInventory___1 extends BaseProcessClass {
	private static final String DELEGATOR = "reportInventoryDelegator";

	public void step1_OnStepProcess_0() throws Exception {
		// 		Step1->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "step1", this);

	}

	public void prepare_OnStepProcess_0() throws Exception {
	// 		Prepare->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "prepare", this);
	}


	public void preSubmitFile_OnStepProcess_0() throws Exception {
	// 		PreSubmitFile->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "preSubmitFile", this);
	}

	public void doSubmit_OnStepProcess_0() throws Exception {
	// 		DoSubmit->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "doSubmit", this);
	}

}
