/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;

import sop.webflow.rt.api.BaseProcessClass;

public class INTRANET___MohRegulation___1 extends BaseProcessClass {

	private static final String DELEGATOR ="hcsaRegulationDelegator";
	
	public void preLoad_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preLoad", this);
	}

	public void doDelete_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doDelete", this);
	}

	public void doPage_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doPage", this);
	}

	public void doSort_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doSort", this);
	}

	public void preUpload_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preUpload", this);
	}

	public void preUpdate_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preUpdate", this);
	}

	public void preCreate_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preCreate", this);
	}

	public void submitUpload_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "submitUpload", this);
	}

	public void doCreateOrUpdate_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doCreateOrUpdate", this);
	}

	public void step1_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "startStep", this);
	}

	public void doQuery_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doQuery", this);
	}

	public void step2_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "step2", this);
	}

}
