/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;

import sop.webflow.rt.api.BaseProcessClass;

public class INTRANET___MohProfessionalInformation___1 extends BaseProcessClass {
	private static final String DELEGATOR ="professionalInformationDelegator";
	
	public void preLoad_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preLoad", this);
	}

	public void switchAction_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "switchAction", this);
	}

	public void preLoadProfessionalDetails_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preLoadProfessionalDetails", this);
	}

	public void doSearch_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doSearch", this);
	}

	public void changePage_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "changePage", this);
	}

	public void sortRecords_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "sortRecords", this);
	}

	public void step1_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "startStep", this);
	}

}
