/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;
import sop.webflow.rt.api.BaseProcessClass;

public class INTRANET___MohAO1ValidateEmail___1 extends BaseProcessClass {
	private static final String DELEGATOR ="validateEmailDelegator";

	public void previewEmail_OnStepProcess_0 () throws Exception { 
	 
		
				EngineHelper.delegate(DELEGATOR, "previewEmail", this); 	}

	public void start_OnStepProcess_0 () throws Exception { 
	 
		
				EngineHelper.delegate(DELEGATOR, "start", this); 	}

	public void prepareData_OnStepProcess_0 () throws Exception { 
	 
		 
			
				EngineHelper.delegate(DELEGATOR, "prepareData", this); 	}

	public void sendEmail_OnStepProcess_0 () throws Exception { 
	 
		
				EngineHelper.delegate(DELEGATOR, "sendEmail", this); 	}

	public void doRecallEmail_OnStepProcess_0 () throws Exception { 
	 
		
				EngineHelper.delegate(DELEGATOR, "doRecallEmail", this);
			}

	

	public void emailSubmitStep_OnStepProcess_0 () throws Exception { 
	 
		
				EngineHelper.delegate(DELEGATOR, "emailSubmitStep", this); 	}

	public void preEmailView_OnStepProcess_0 () throws Exception { 
	 
		
				EngineHelper.delegate(DELEGATOR, "preEmailView", this);
			}

	public void checkListNext_OnStepProcess_0 () throws Exception { 
	 
		
				EngineHelper.delegate(DELEGATOR, "checkListNext", this);
			}

	public void preCheckList_OnStepProcess_0 () throws Exception { 
	 
		
				EngineHelper.delegate(DELEGATOR, "preCheckList", this);
			}

	public void emailView_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "emailView", this);
	// 		emailView->OnStepProcess
	}

	public void preProcess_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preProcess", this);
// 		preProcess->OnStepProcess
	}

	public void doProcessing_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doProcessing", this);
// 		doProcessing->OnStepProcess
	}

}
