/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;

import sop.webflow.rt.api.BaseProcessClass;

public class INTRANET___MohInspectionReport___1 extends BaseProcessClass {

	private static final String DELEGATOR ="insReport";
	
	public void step1_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "start", this);
	}

	public void inspectionReportInit_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "inspectionReportInit", this);
	}

	public void inspectorReportPre_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "inspectionReportPre", this);
	}

	public void inspectorReportSave_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "inspectorReportSave", this);
	}

	public void preCheckList_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preCheckList", this);
// 		preCheckList->OnStepProcess
	}

	public void checkListNext_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "checkListNext", this);
// 		checkListNext->OnStepProcess
	}

	public void setMulAction_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preViewCheckList", this);
	// 		setMulAction->OnStepProcess
	}

	public void doChecklist_OnStepProcess_0() throws Exception {
	// 		doChecklist->OnStepProcess
	}

	public void saveChecklist_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doCheckList", this);
// 		saveChecklist->OnStepProcess
	}

}
