/*
 *   This file is generated by ECQ project skeleton automatically.
 *
 *   Copyright 2019-2049, Ecquaria Technologies Pte Ltd. All rights reserved.
 *
 *   No part of this material may be copied, reproduced, transmitted,
 *   stored in a retrieval system, reverse engineered, decompiled,
 *   disassembled, localised, ported, adapted, varied, modified, reused,
 *   customised or translated into any language in any form or by any means,
 *   electronic, mechanical, photocopying, recording or otherwise,
 *   without the prior written permission of Ecquaria Technologies Pte Ltd.
 */

package com.ecquaria.cloud.moh.iais.tags;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.Spy;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.api.mockito.mockpolicies.Slf4jMockPolicy;
import org.powermock.core.classloader.annotations.MockPolicy;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;
import org.powermock.reflect.Whitebox;

import javax.servlet.jsp.JspException;
import javax.servlet.jsp.JspTagException;
import javax.servlet.jsp.JspWriter;
import javax.servlet.jsp.PageContext;
import java.io.IOException;

import static org.junit.Assert.assertEquals;
import static org.mockito.Matchers.anyString;
import static org.powermock.api.mockito.PowerMockito.doNothing;
import static org.powermock.api.mockito.PowerMockito.doThrow;
import static org.powermock.api.mockito.PowerMockito.when;

/**
 * SectionTagTest
 *
 * @author suocheng
 * @date 8/6/2019
 */
@RunWith(PowerMockRunner.class)
@MockPolicy(Slf4jMockPolicy.class)
@PrepareForTest({SectionTag.class})
public class SectionTagTest {
    @Spy
    private SectionTag tag = new SectionTag();
    @Mock
    private JspWriter jw;

    @Before
    public void setup() throws IOException {
        PageContext pageContext = PowerMockito.mock(PageContext.class);
        Whitebox.setInternalState(tag, "pageContext", pageContext);
        when(pageContext.getOut()).thenReturn(jw);
        doNothing().when(jw).print(anyString());
        tag.setId("idd");
        tag.setStyle("ssss");
        tag.setTitle("title");
        tag.setCollapse(true);
        tag.setReload(true);
        tag.setRemove(true);
        tag.setRemoveToHide(true);
        tag.setHide(true);
        tag.setEnable(true);

    }

    @Test
    public void testGet(){
        String tltle = tag.getTitle();
        Assert.assertEquals("title",tltle);
        Assert.assertTrue(tag.isCollapse());
        Assert.assertTrue(tag.isReload());
        Assert.assertTrue(tag.isRemove());
        Assert.assertTrue(tag.isRemoveToHide());
        Assert.assertTrue(tag.isHide());
        Assert.assertTrue(tag.isEnable());
    }
    @Test
    public void testdoStartTag() throws JspException {
        int ret = tag.doStartTag();
        assertEquals(SectionTag.EVAL_BODY_INCLUDE, ret);
    }
    @Test(expected = JspTagException.class)
    public void testDoStartTagExp() throws JspException, IOException {
        doThrow(new RuntimeException()).when(jw).print(anyString());
        int ret = tag.doStartTag();
    }
    @Test
    public void testDoEndTag() throws JspException {
        int ret = tag.doEndTag();
        assertEquals(SectionTag.EVAL_PAGE, ret);
        tag.release();
    }

    @Test(expected = JspTagException.class)
    public void testDoEndTagExp() throws JspException, IOException {
        doThrow(new RuntimeException()).when(jw).print(anyString());
        int ret = tag.doEndTag();
    }
}
