/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;

import sop.webflow.rt.api.BaseProcessClass;

public class INTRANET___MohAduitSystemList___1 extends BaseProcessClass {
	private static final String DELEGATOR ="auditSystemListDelegator";
	public void start_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "start", this);
	}

	public void init_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "init", this);
	}

	public void pre_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "pre", this);
	}

	public void vad_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "vad", this);
	}

	public void next_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "next", this);
	}

	public void listpageNext_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "listpageNext", this);
	}

	public void remove_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "remove", this);
	}

	public void confirm_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "confirm", this);
	}

	public void precreatehcl_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "precreatehcl", this);
	}

	public void precanceltask_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "precanceltask", this);
	}

	public void submit_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "submit", this);
	}

	public void createhcl_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "createhcl", this);
	}

	public void canceltask_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "canceltask", this);
	}

}
