/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;
import sop.webflow.rt.api.BaseProcessClass;

public class INTERNET___MohLicenseeCompanyDetail___1 extends BaseProcessClass {
	private static final String DELEGATOR ="licenseeCompanyDelegate";
	public void step1_OnStepProcess_0() throws Exception {
		// 		Step1->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "start", this);
		}
	public void prepare_OnStepProcess_0() throws Exception {
	// 		Prepare->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "prepare", this);
	}
	public void company_OnStepProcess_0() throws Exception {
	// 		Company->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "company", this);
	}
	public void solo_OnStepProcess_0() throws Exception {
	// 		Solo->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "solo", this);
	}
	public void backToMenu_OnStepProcess_0() throws Exception {
	// 		backToMenu->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "backToMenu", this);
	}
	public void licensee_OnStepProcess_0() throws Exception {
	// 		Licensee->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "licensee", this);
	}
	public void authorised_OnStepProcess_0() throws Exception {
	// 		Authorised->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "authorised", this);
	}
	public void medAlert_OnStepProcess_0() throws Exception {
	// 		MedAlert->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "medAlert", this);
	}
	

}
