/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

import sop.webflow.process5.util.FileUtil;
import sop.webflow.rt.api.BaseProcessClass;

public class SYSTEM___MyInfoPropertyLoad___1 extends BaseProcessClass {

	public void loadData_OnStepProcess_0() throws Exception {
	// 		loadData->OnStepProcess
		 File file=new File(FileUtil.BIN_TO_SOP + "WEB-INF/classes/myinfoproperty.json");
         if(!file.exists()||file.isDirectory())
             throw new FileNotFoundException();
         FileInputStream fis=new FileInputStream(file);
         byte[] buf = new byte[1024];
         StringBuffer sb=new StringBuffer();
         while((fis.read(buf))!=-1){
             sb.append(new String(buf));    
             buf=new byte[1024];//
         }
         fis.close();
		
		try 
        {
            BufferedReader in = new BufferedReader(new FileReader(file));
            String str = "";
            String temp = "";
            while ((str = in.readLine()) != null) 
            {
            	temp+=str;
            }
           
            in.close();
 
            request.setAttribute("propertyMap",temp);
        } 
        catch (IOException e) 
        {
            e.getStackTrace();
        }

		
	}

}
