name: ${TagName}-${BUILD_NUMBER}
project_name: IAIS
env_name: P2_IAIS_INTERNET
description: |
  This production deployment package is for deployment release no. ${TagName}-${BUILD_NUMBER}.
  It contains the fixes/changes made for the following issue(s):
  1) Just a simple deployment test on IAIS_INTERNET

execution: manual
failure_action: stop

deployments:
  - type: image_tag
    stack_name: fe-iais-app
    services:
      - hcsa-licence-web=hub.ecquaria.com:8152/docker-mohiais-egp/hcsa-application:${TagName}-${BUILD_NUMBER}
      - main-web=hub.ecquaria.com:8152/docker-mohiais-egp/fe-main:${TagName}-${BUILD_NUMBER}
      - egov-app=hub.ecquaria.com:8152/docker-mohiais-egp/egov-app:${TagName}-${BUILD_NUMBER}
      - web=hub.ecquaria.com:8152/docker-mohiais-egp/web:${TagName}-${BUILD_NUMBER}
  - type: wait_for_healthcheck
    stack_name: fe-iais-app
    timeout_seconds: 300
  - type: image_tag
    stack_name: bsb-fe-egp
    services:
      - bsb-web=hub.ecquaria.com:8152/docker-mohiais-egp/bsb-fe:${TagName}-${BUILD_NUMBER}
  - type: wait_for_healthcheck
    stack_name: bsb-fe-egp
    timeout_seconds: 300