/*
 *   This file is generated by ECQ project skeleton automatically.
 *
 *   Copyright 2019-2049, Ecquaria Technologies Pte Ltd. All rights reserved.
 *
 *   No part of this material may be copied, reproduced, transmitted,
 *   stored in a retrieval system, reverse engineered, decompiled,
 *   disassembled, localised, ported, adapted, varied, modified, reused,
 *   customised or translated into any language in any form or by any means,
 *   electronic, mechanical, photocopying, recording or otherwise,
 *   without the prior written permission of Ecquaria Technologies Pte Ltd.
 */

package com.ecquaria.cloud.moh.iais.dao;

import com.ecquaria.cloud.moh.iais.entity.FormTest;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * Class description
 *
 * @author suocheng
 * @date 7/4/2019
 */
public interface FormTestDao extends JpaRepository<FormTest, Long> {

}
