/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;
import sop.webflow.rt.api.BaseProcessClass;

public class INTERNET___ApplicantCancellationApproval___1 extends BaseProcessClass {

	private static final String DELEGATOR ="applicantCancellationAppDelegator";
	
	public void start_OnStepProcess_0() throws Exception {
	// 		Start->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "start", this);
	}

	public void init_OnStepProcess_0() throws Exception {
	// 		Init->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "init", this);
	}

	public void validCommit_OnStepProcess_0() throws Exception {
	// 		ValidCommit->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "validCommit", this);
	}

	public void preparePreview_OnStepProcess_0() throws Exception {
	// 		PreparePreview->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "preparePreview", this);
	}

	public void doSaveSubmit_OnStepProcess_0() throws Exception {
	// 		DoSaveSubmit->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "doSaveSubmit", this);
	}

	public void doPreview_OnStepProcess_0() throws Exception {
	// 		DoPreview->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "doPreview", this);
	}

}
