/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import sop.webflow.rt.api.BaseProcessClass;

public class INTERNET___AckOfReceiptOfTransfer___1 extends BaseProcessClass {

	public void start_OnStepProcess_0() throws Exception {
	// 		start->OnStepProcess
	}

	public void prepareData_OnStepProcess_0() throws Exception {
	// 		prepareData->OnStepProcess
	}

	public void saveAndPreConfirm_OnStepProcess_0() throws Exception {
	// 		saveAndPreConfirm->OnStepProcess
	}

	public void save_OnStepProcess_0() throws Exception {
	// 		save->OnStepProcess
	}

}
