/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;
import sop.webflow.rt.api.BaseProcessClass;

public class INTERNET___MohDPDataSumission___1 extends BaseProcessClass {
    
    private static final long serialVersionUID = 1L;
    
    private static final String DELEGATOR = "dpDataSubmissionDelegator";

    public void start_OnStepProcess_0() throws Exception {
    // 		Start->OnStepProcess
        EngineHelper.delegate(DELEGATOR, "doStart", this);
    }

    public void prepareSubmission_OnStepProcess_0() throws Exception {
    // 		PrepareSubmission->OnStepProcess
        EngineHelper.delegate(DELEGATOR, "doPrepareSubmission", this);
    }

    public void prepareDP_OnStepProcess_0() throws Exception {
    // 		PrepareDP->OnStepProcess
        EngineHelper.delegate(DELEGATOR, "doPrepareDP", this);
    }

    public void preparePatientInfo_OnStepProcess_0() throws Exception {
    // 		PreparePatientInfo->OnStepProcess
        EngineHelper.delegate(DELEGATOR, "preparePatientInfo", this);
    }

    public void prepareDrugPrecribed_OnStepProcess_0() throws Exception {
    // 		PrepareDrugPrecribed->OnStepProcess
        EngineHelper.delegate(DELEGATOR, "prepareDrugPrecribed", this);
    }

    public void prepareSovenorInventory_OnStepProcess_0() throws Exception {
    // 		PrepareSovenorInventory->OnStepProcess
        EngineHelper.delegate(DELEGATOR, "prepareSovenorInventory", this);
    }

    public void prepareReturn_OnStepProcess_0() throws Exception {
    // 		PrepareReturn->OnStepProcess
        EngineHelper.delegate(DELEGATOR, "prepareReturn", this);
    }

}
