/*
 * This file is generated by ECQ project skeleton automatically.
 *
 *   Copyright 2019-2049, Ecquaria Technologies Pte Ltd. All rights reserved.
 *
 *   No part of this material may be copied, reproduced, transmitted,
 *   stored in a retrieval system, reverse engineered, decompiled,
 *   disassembled, localised, ported, adapted, varied, modified, reused,
 *   customised or translated into any language in any form or by any means,
 *   electronic, mechanical, photocopying, recording or otherwise,
 *   without the prior written permission of Ecquaria Technologies Pte Ltd.
 */

package com.ecquaria.cloud.moh.iais.dto;


import com.ecquaria.cloud.moh.iais.common.utils.MiscUtil;
import com.ecquaria.cloud.moh.iais.common.validation.annotations.CustomValidate;
import com.ecquaria.cloud.moh.iais.validate.AuditTrailDtoValidate;
import com.ecquaria.cloud.moh.iais.web.logging.dto.AuditTrailDto;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.util.Date;

@Getter
@Setter
@CustomValidate(impClass = AuditTrailDtoValidate.class, properties = {"query"})
public
class AuditTrailQueryDto implements Serializable {
    private static final ThreadLocal<AuditTrailDto> threadContext = new ThreadLocal<>();
    private static final long serialVersionUID = -6184748147127672799L;

    private Integer auditId;

    private Date actionTime;
    private int operation;
    private String  nricNumber;
    private String  uenId;
    private String  mohUserId;
    private int loginType;
    private String  sessionId;
    private String  clientIp;
    private String  userAgent;
    private String  appNum;
    private String  licenseNum;
    private String  module;
    private String  functionName;
    private String  programmeName;
    private String  beforeAction;
    private String  afterAction;
    private String  validationFail;
    private String  viewParams;
    private String  failReason;
/*
    @ValidateWithMethod(methodName= "validTime", parameterType = Date.class, profiles = "query", message = "Search time to be 3 months or less.")
    private Date startTime;

    @ValidateWithMethod(methodName= "valiEndTime", parameterType = Date.class, profiles = "query", message = "Search time to be 3 months or less.")
    private Date endTime;

    public boolean valiStartTime(Date startTime){
        System.out.println("startTime" + startTime);
        System.out.println("endTime" + endTime);
        return false;
    }

    public boolean valiEndTime(Date startTime){
        System.out.println("startTime" + startTime);
        System.out.println("endTime" + endTime);
        return false;
    }*/

    public
    static com.ecquaria.cloud.moh.iais.web.logging.dto.AuditTrailDto getThreadDto() {
    com.ecquaria.cloud.moh.iais.web.logging.dto.AuditTrailDto dto = threadContext.get();
        if (dto == null)
        return null;

        return MiscUtil.transferEntityDto(dto, com.ecquaria.cloud.moh.iais.web.logging.dto.AuditTrailDto.class);
    }

    public
    static void setThreadDto(com.ecquaria.cloud.moh.iais.web.logging.dto.AuditTrailDto dto) {
        threadContext.set(dto);
    }

    public
    static void removeThreadDto() {
        threadContext.remove();
    }
}
