/*
 * This file is generated by ECQ project skeleton automatically.
 *
 *   Copyright 2019-2049, Ecquaria Technologies Pte Ltd. All rights reserved.
 *
 *   No part of this material may be copied, reproduced, transmitted,
 *   stored in a retrieval system, reverse engineered, decompiled,
 *   disassembled, localised, ported, adapted, varied, modified, reused,
 *   customised or translated into any language in any form or by any means,
 *   electronic, mechanical, photocopying, recording or otherwise,
 *   without the prior written permission of Ecquaria Technologies Pte Ltd.
 */

package com.ecquaria.cloud.moh.iais.helper;

import lombok.extern.slf4j.Slf4j;

/**
 * SqlHelper
 *
 * @author Jinhua
 * @date 2019/7/18 17:17
 */
@Slf4j
public class SqlHelper {

    /**
     * @description: The method to get in SQL with param
     *
     * @author: Jinhua on 2019/7/23 10:48
     * @param: [fieldName, size]
     * @return: java.lang.String
     */
    public static String constructInCondition(String fieldName, int size) {
        StringBuffer sBuffer = new StringBuffer();
        if (size > 0){
            sBuffer.append(" ((").append(fieldName).append(" in (:").append(fieldName).append(0);

            int counter = 1;
            for (int i = 1; i < size; i++) {
                if (counter < 900) {
                    sBuffer.append(", :").append(fieldName).append(i);
                    counter++;
                } else {
                    //split for every 900 elements
                    sBuffer.append(")) or (").append(fieldName).append(" in (:").append(fieldName).append(i);
                    counter = 0;
                }
            }

            sBuffer.append(")))");
        }else{
            sBuffer.append(" 1 = 2 ");
        }

        return sBuffer.toString();
    }


    private SqlHelper() {throw new IllegalStateException("Utility class");}
}
