/*
 *   This file is generated by ECQ project skeleton automatically.
 *
 *   Copyright 2019-2049, Ecquaria Technologies Pte Ltd. All rights reserved.
 *
 *   No part of this material may be copied, reproduced, transmitted,
 *   stored in a retrieval system, reverse engineered, decompiled,
 *   disassembled, localised, ported, adapted, varied, modified, reused,
 *   customised or translated into any language in any form or by any means,
 *   electronic, mechanical, photocopying, recording or otherwise,
 *   without the prior written permission of Ecquaria Technologies Pte Ltd.
 */

package com.ecquaria.cloud.moh.iais.tags;

import sg.gov.moh.iais.common.utils.AccessUtil;
import sg.gov.moh.iais.common.utils.StringUtil;

import javax.servlet.jsp.JspException;
import javax.servlet.jsp.JspTagException;

/**
 * Body Tag
 *
 *
 * @date        7/23/2019
 * @author      suocheng
 */
public final class BodyTag extends DivTagSupport {
    private static final long serialVersionUID = 2507648507715155034L;

    private boolean disabled;

    public BodyTag() {
        super();
        init();
    }

    // resets local state
    protected void init() {
        super.init();
    }

    public void release() {
        super.release();
        init();
    }

    public int doStartTag() throws JspException {
        StringBuffer html = new StringBuffer();
        boolean isBE = AccessUtil.isBackend();
        if (isBE) {
            html.append("<iframe id=\"txtArea1\" style=\"display:none\"></iframe>");
            html.append("<div class=\"dash-content dash-r-bg");
        } else {
            html.append("<div class=\"subcontent col-lg-12 col-sm-12");
        }
        html.append("\"");
        if (!StringUtil.isEmpty(id)) {
            html.append(" id=\"").append(id).append("\"");
        }
        if (!StringUtil.isEmpty(style)) {
            html.append(" style=\"").append(style).append("\"");
        }
        html.append(">");
        // body
        try {
            pageContext.getOut().print(StringUtil.escapeSecurityScript(html.toString()));
        } catch (Exception ex) {
            throw new JspTagException("RowTag: " + ex.getMessage());
        }
        return EVAL_BODY_INCLUDE;
    }

    public int doEndTag() throws JspException {
        try {
            pageContext.getOut().print("</div>");
        } catch (Exception ex) {
            throw new JspTagException("RowTag: " + ex.getMessage());
        }
        return EVAL_PAGE;
    }

    public boolean isDisabled() {
        return disabled;
    }

    public void setDisabled(boolean disabled) {
        this.disabled = disabled;
    }
}
