/*
 *   This file is generated by ECQ project skeleton automatically.
 *
 *   Copyright 2019-2049, Ecquaria Technologies Pte Ltd. All rights reserved.
 *
 *   No part of this material may be copied, reproduced, transmitted,
 *   stored in a retrieval system, reverse engineered, decompiled,
 *   disassembled, localised, ported, adapted, varied, modified, reused,
 *   customised or translated into any language in any form or by any means,
 *   electronic, mechanical, photocopying, recording or otherwise,
 *   without the prior written permission of Ecquaria Technologies Pte Ltd.
 */

package com.ecquaria.cloud.moh.iais.tags;

import sg.gov.moh.iais.common.utils.AccessUtil;
import sg.gov.moh.iais.common.utils.StringUtil;

import javax.servlet.jsp.JspException;
import javax.servlet.jsp.JspTagException;

/**
 * SearchSectionTag
 *
 *
 * @date        7/23/2019
 * @author      suocheng
 */
public final class SearchSectionTag extends DivTagSupport {

    private static final long serialVersionUID = 5208105145123011150L;
    private String title;
    private boolean collapse;
    private boolean reload;
    private boolean remove;
    private boolean hide;

    private String onclick;
    private String placeholder;
    private String fieldName;
    private String value;

    public SearchSectionTag() {
        super();
        init();
    }

    // resets local state
    protected void init() {
        super.init();
        title = null;
        fieldName = "";
        value = "";
    }

    public void release() {
        super.release();
        init();
    }

    public int doStartTag() throws JspException {
        StringBuffer html = new StringBuffer();

        boolean isBE = AccessUtil.isBackend();
        // header
        html.append("<div class=\"epd_tb collapsed\">");
        if (isBE) {
            html.append("<div class=\"dash-header epdtitle\">");
            html.append("<div class=\"row\">");
            html.append("<div class=\"col-sm-12 col-md-12 col-lg-9 wsearch\">").append(title).append("</div>");
            html.append("<div class=\"col-sm-12 col-md-12 col-lg-3 searchspacing\">");
            if (!StringUtil.isEmpty(onclick)) {
                html.append("<div class=\"search-iconic-input\">");
                html.append("<a href=\"javascript:void(0);\"");

                html.append(" onclick=\"").append(onclick).append("\"");

                html.append("><i class=\"fa fa-search\"></i></a>");
                html.append("<input type=\"text\" class=\"form-control search-box\" placeholder=\"").append(placeholder).append("\"");
                html.append(" name=\"").append(fieldName).append("\"");
                if (!StringUtil.isEmpty(value)) {
                    html.append(" value=\"").append(StringUtil.escapeHtml(value)).append("\"");
                }
                html.append("></div>");
            }
            html.append("</div>");
            html.append("</div>");
            html.append("</div>");
            // body
            html.append("<div class=\"dash-body no-dash-pads epdct_tb\"");
            if (hide) {
                html.append(" style=\"display:none;\"");
            }
            html.append(">");
        } else {
            html.append("<div class=\"epdtitle epdtitle_tb1\">");
            html.append("<div class=\"floatleft bold\"><span><font12>").append(title).append("</font12></span></div>");
            html.append("<div class=\"floatright\">");
            if (!StringUtil.isEmpty(onclick)) {
                html.append("<div class=\"search-iconic-input\">");
                html.append("<a href=\"javascript:void(0);\"");
                html.append(" onclick=\"").append(onclick).append("\"");
                html.append("><i class=\"fa fa-search\"></i></a>");
                html.append("<input type=\"text\" class=\"searchapp searchwidth no-form-control\" placeholder=\"").append(placeholder).append("\"");
                html.append(" alt=\"").append(placeholder).append("\"");
                html.append(" name=\"").append(fieldName).append("\"");
                if (!StringUtil.isEmpty(value)) {
                    html.append(" value=\"").append(StringUtil.escapeHtml(value)).append("\"");
                }
                html.append("></div>");
            }

            html.append("</div>");
            html.append("<div class=\"clear\"></div>");
            html.append("</div>");
            // body
            html.append("<div class=\"epdct_tb\"");
            if (hide) {
                html.append(" style=\"display:none;\"");
            }
            html.append(">");
        }
        try {
            pageContext.getOut().print(StringUtil.escapeSecurityScript(html.toString()));
        } catch (Exception ex) {
            throw new JspTagException("RowTag: " + ex.getMessage());
        }
        return EVAL_BODY_INCLUDE;
    }

    public int doEndTag() throws JspException {
        try {
            pageContext.getOut().print("</div></div>");
        } catch (Exception ex) {
            throw new JspTagException("RowTag: " + ex.getMessage());
        }
        return EVAL_PAGE;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setCollapse(boolean collapse) {
        this.collapse = collapse;
    }

    public boolean isCollapse() {
        return collapse;
    }

    public boolean isReload() {
        return reload;
    }

    public void setReload(boolean reload) {
        this.reload = reload;
    }

    public void setRemove(boolean remove) {
        this.remove = remove;
    }

    public boolean isRemove() {
        return remove;
    }

    public void setHide(boolean hide) {
        this.hide = hide;
    }

    public void setOnclick(String onclick) {
        this.onclick = onclick;
    }

    public void setPlaceholder(String placeholder) {
        this.placeholder = placeholder;
    }

    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
