/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;
import sop.webflow.rt.api.BaseProcessClass;

public class INTRANET___FeeAndPaymentGIROPayee___1 extends BaseProcessClass {
	private static final String DELEGATOR ="feeAndPaymentGIROPayeeDelegator";
	
	public void start_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "start", this); 
		// 		start->OnStepProcess
	}

	public void info_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "info", this); 
		// 		info->OnStepProcess
	}

	public void prePayeeResult_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "prePayeeResult", this); 
		// 		prePayeeResult->OnStepProcess
	}

	public void deletePayee_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "deletePayee", this); 
		// 		deletePayee->OnStepProcess
	}

	public void reSearchPayee_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "reSearchPayee", this); 
		// 		reSearchPayee->OnStepProcess
	}

	public void preOrgResult_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preOrgResult", this); 
		// 		preOrgResult->OnStepProcess
	}

	public void reSearchOrg_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "reSearchOrg", this); 
		// 		reSearchOrg->OnStepProcess
	}

	public void doSelect_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doSelect", this); 
		// 		doSelect->OnStepProcess
	}

	public void doBack_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doBack", this); 
		// 		doBack->OnStepProcess
	}

	public void refill_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "refill", this); 
		// 		refill->OnStepProcess
	}

	public void doValidate_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doValidate", this); 
		// 		doValidate->OnStepProcess
	}

	public void preView_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preView", this); 
		// 		preView->OnStepProcess
	}

	public void doSubmit_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doSubmit", this); 
		// 		doSubmit->OnStepProcess
	}

	public void backPayee_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "backPayee", this); 

	// 		backPayee->OnStepProcess
	}

	public void doSwich_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doSwich", this); 

	// 		doSwich->OnStepProcess
	}

}
