/*
 *   This file is generated by ECQ project skeleton automatically.
 *
 *   Copyright 2019-2049, Ecquaria Technologies Pte Ltd. All rights reserved.
 *
 *   No part of this material may be copied, reproduced, transmitted,
 *   stored in a retrieval system, reverse engineered, decompiled,
 *   disassembled, localised, ported, adapted, varied, modified, reused,
 *   customised or translated into any language in any form or by any means,
 *   electronic, mechanical, photocopying, recording or otherwise,
 *   without the prior written permission of Ecquaria Technologies Pte Ltd.
 */

package com.ecquaria.cloud.moh.iais.validate;

import com.ecquaria.cloud.helper.SpringContextHelper;
import com.ecquaria.cloud.moh.iais.action.OrgUserAccountDelegator;
import com.ecquaria.cloud.moh.iais.common.utils.ParamUtil;
import com.ecquaria.cloud.moh.iais.dto.OrgUserAccountDto;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Spy;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.api.mockito.mockpolicies.Slf4jMockPolicy;
import org.powermock.core.classloader.annotations.MockPolicy;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;
import org.springframework.context.ApplicationContext;
import org.springframework.mock.web.MockHttpServletRequest;
import sop.util.Assert;

import java.util.Map;

import static org.powermock.api.mockito.PowerMockito.when;

/**
 * OrgUserAccountValidateTest
 *
 * @author suocheng
 * @date 8/7/2019
 */
@RunWith(PowerMockRunner.class)
@MockPolicy(Slf4jMockPolicy.class)
@PrepareForTest({OrgUserAccountValidate.class,SpringContextHelper.class})
public class OrgUserAccountValidateTest {
    @Spy
    private OrgUserAccountValidate orgUserAccountValidate = new OrgUserAccountValidate();
    private MockHttpServletRequest request = new MockHttpServletRequest();
//    @Mock
//    private OrgUserAccountDao orgUserAccountDao ;

    @Before
    public void setup(){
        PowerMockito.mockStatic(SpringContextHelper.class);
        ApplicationContext context = PowerMockito.mock(ApplicationContext.class);
        when(SpringContextHelper.getContext()).thenReturn(context);
       // doReturn(orgUserAccountDao).when(context).getBean(OrgUserAccountDao.class);
    }

    @Test
    public void testValidate(){
        OrgUserAccountDto orgUserAccountDto = new OrgUserAccountDto();
        orgUserAccountDto.setNircNo("NircNo");
        orgUserAccountDto.setId(0);
        ParamUtil.setSessionAttr(request, OrgUserAccountDelegator.ORG_USER_DTO_ATTR,orgUserAccountDto);

//        OrgUserAccount oua = new OrgUserAccount();
//        oua.setId(1);
//        PowerMockito.when(orgUserAccountDao.findByIdNo(Mockito.anyObject())).thenReturn(oua);

        Map<String,String> errorMap = orgUserAccountValidate.validate(request);
        Assert.assertNotNull(errorMap);
    }
}
