/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;
import sop.webflow.rt.api.BaseProcessClass;

public class INTERNET___MohInspecUserRectifiUpload___1 extends BaseProcessClass {

	private static final long serialVersionUID = 7917069619703332081L;
	private static final String DELEGATOR ="inspecUserRecUploadDelegator";

	public void inspecUserRectifiUploadStart_OnStepProcess_0() throws Exception {
	// 		InspecUserRectifiUploadStart->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspecUserRectifiUploadStart", this);
	}

	public void inspecUserRectifiUploadInit_OnStepProcess_0() throws Exception {
	// 		InspecUserRectifiUploadInit->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspecUserRectifiUploadInit", this);
	}

	public void inspecUserRectifiUploadPre_OnStepProcess_0() throws Exception {
	// 		InspecUserRectifiUploadPre->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspecUserRectifiUploadPre", this);
	}

	public void inspecUserRectifiUploadVali_OnStepProcess_0() throws Exception {
	// 		InspecUserRectifiUploadVali->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspecUserRectifiUploadVali", this);
	}

	public void inspecUserRectifiUploadConfirm_OnStepProcess_0() throws Exception {
	// 		InspecUserRectifiUploadConfirm->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspecUserRectifiUploadConfirm", this);
	}

	public void inspecUserRectifiUploadSuccess_OnStepProcess_0() throws Exception {
	// 		InspecUserRectifiUploadSuccess->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "inspecUserRectifiUploadSuccess", this);
	}

}
