/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;

import sop.webflow.rt.api.BaseProcessClass;

public class INTERNET___MohFeTcuAuditApptPreDate___1 extends BaseProcessClass {
	
	private static final long serialVersionUID = 2215817143139426760L;
	private static final String DELEGATOR ="tcuAuditApptPreDateDelegator";

	public void feTcuAuditApptPreDateStart_OnStepProcess_0() throws Exception {
	// 		feTcuAuditApptPreDateStart->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "feTcuAuditApptPreDateStart", this);
	}

	public void feTcuAuditApptPreDateInit_OnStepProcess_0() throws Exception {
	// 		feTcuAuditApptPreDateInit->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "feTcuAuditApptPreDateInit", this);
	}

	public void feTcuAuditApptPreDatePre_OnStepProcess_0() throws Exception {
	// 		feTcuAuditApptPreDatePre->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "feTcuAuditApptPreDatePre", this);
	}

	public void feTcuAuditApptPreDateStep_OnStepProcess_0() throws Exception {
	// 		feTcuAuditApptPreDateStep->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "feTcuAuditApptPreDateStep", this);
	}

	public void feTcuAuditApptPreDateVali_OnStepProcess_0() throws Exception {
	// 		feTcuAuditApptPreDateVali->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "feTcuAuditApptPreDateVali", this);
	}

}
