/*
 *   This file is generated by ECQ project skeleton automatically.
 *
 *   Copyright 2019-2049, Ecquaria Technologies Pte Ltd. All rights reserved.
 *
 *   No part of this material may be copied, reproduced, transmitted,
 *   stored in a retrieval system, reverse engineered, decompiled,
 *   disassembled, localised, ported, adapted, varied, modified, reused,
 *   customised or translated into any language in any form or by any means,
 *   electronic, mechanical, photocopying, recording or otherwise,
 *   without the prior written permission of Ecquaria Technologies Pte Ltd.
 */

package com.ecquaria.cloud.moh.iais.demo.service;

import com.ecquaria.cloud.moh.iais.demo.entity.DemoQuery;
import com.ecquaria.cloud.moh.iais.demo.entity.OrgUserAccount;
import sg.gov.moh.iais.common.dto.SearchParam;
import sg.gov.moh.iais.common.dto.SearchResult;

/**
 * OrgUserAccountService
 *
 * @author suocheng
 * @date 7/12/2019
 */
public interface OrgUserAccountService {

 public void deleteOrgUserAccountsById(String id);
 public void saveOrgUserAccounts(OrgUserAccount orgUserAccount);
 public OrgUserAccount getOrgUserAccountByRowguId(String rowguId);
 public SearchResult<DemoQuery> doQuery(SearchParam param, String catalog, String key);
}
