/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;
import sop.webflow.rt.api.BaseProcessClass;

public class INTERNET___MohWithOutRenewal___1 extends BaseProcessClass {
	private static final String DELEGATOR ="withOutRenewalDelegator";
	public void preparatData_OnStepProcess_0() throws Exception {
	// 		preparatData->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "prepare", this);
	}
	public void start_OnStepProcess_0() throws Exception {
	// 		Start->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "start", this);
	}
	public void selectLience_OnStepProcess_0() throws Exception {
	// 		SelectLience->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "determineAutoRenewalEligibility", this);
	}
	public void prepareJump_OnStepProcess_0() throws Exception {
	// 		prepareJump->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "prepareJump", this);
	}
	public void toPrepareData_OnStepProcess_0() throws Exception {
	// 		toPrepareData->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "toPrepareData", this);
	}

}
