/*
 * This file is generated by ECQ project skeleton automatically.
 *
 *   Copyright 2019-2049, Ecquaria Technologies Pte Ltd. All rights reserved.
 *
 *   No part of this material may be copied, reproduced, transmitted,
 *   stored in a retrieval system, reverse engineered, decompiled,
 *   disassembled, localised, ported, adapted, varied, modified, reused,
 *   customised or translated into any language in any form or by any means,
 *   electronic, mechanical, photocopying, recording or otherwise,
 *   without the prior written permission of Ecquaria Technologies Pte Ltd.
 */

package com.ecquaria.cloud.moh.iais.sql;

import com.ecquaria.cloud.helper.ConfigHelper;
import com.ecquaria.cloud.moh.iais.common.exception.IaisRuntimeException;
import com.ecquaria.cloud.moh.iais.common.utils.IaisCommonUtils;
import com.ecquaria.cloud.moh.iais.common.utils.StringUtil;
import freemarker.cache.StringTemplateLoader;
import freemarker.core.TemplateClassResolver;
import freemarker.template.Configuration;
import freemarker.template.Template;
import freemarker.template.TemplateException;
import lombok.extern.slf4j.Slf4j;

import java.io.IOException;
import java.io.StringWriter;
import java.util.List;
import java.util.Map;

/**
 * SqlMap
 *
 * @author Jinhua
 * @date 2019/7/18 17:21
 */
@Slf4j
public class SqlMap {
    public static final SqlMap INSTANCE = new SqlMap();
    private final Map<String, Sql> mapforSql;
    private Map<String, String> dbNameMap;
    private static final Configuration cfg = new Configuration(Configuration.VERSION_2_3_28);

    public void initSqlMap(List<Sql> sqls) {
        StringTemplateLoader loader = new StringTemplateLoader();
        for (Sql sql : sqls) {
            String key = getKey(sql.getCatalog(), sql.getKey());
            mapforSql.put(key, sql);
            if (isDynamicSql(sql.getSqlStr())) {
                loader.putTemplate(key, sql.getSqlStr());
            }
        }
        cfg.setTemplateLoader(loader);
        cfg.setNewBuiltinClassResolver(TemplateClassResolver.SAFER_RESOLVER);

        //init DB name
        dbNameMap = IaisCommonUtils.genNewHashMap();
        dbNameMap.put("hcsal", ConfigHelper.getString("iais.dbname.hcsal", "hcsal"));
        dbNameMap.put("hcsala", ConfigHelper.getString("iais.dbname.hcsala", "hcsala"));
        dbNameMap.put("hcsalm", ConfigHelper.getString("iais.dbname.hcsalm", "hcsalm"));
        dbNameMap.put("iaismstr", ConfigHelper.getString("iais.dbname.iaismstr", "iaismstr"));
        dbNameMap.put("organization", ConfigHelper.getString("iais.dbname.organization", "organization"));
        dbNameMap.put("biospa", ConfigHelper.getString("iais.dbname.biospa", "biospa"));
        dbNameMap.put("audittrail", ConfigHelper.getString("iais.dbname.audittrail", "audittrail"));
        dbNameMap.put("egpcloud", ConfigHelper.getString("iais.dbname.egpcloud", "egpcloud"));
        dbNameMap.put("edrdb", ConfigHelper.getString("iais.dbname.edrdb", "edrdb"));
        dbNameMap.put("filerepo", ConfigHelper.getString("iais.dbname.filerepo", "filerepo"));
        dbNameMap.put("inetbox", ConfigHelper.getString("iais.dbname.inetbox", "inetbox"));
        dbNameMap.put("onlpymt", ConfigHelper.getString("iais.dbname.onlpymt", "onlpymt"));
        dbNameMap.put("onlappt", ConfigHelper.getString("iais.dbname.onlappt", "onlappt"));
        dbNameMap.put("smemail", ConfigHelper.getString("iais.dbname.smemail", "smemail"));
    }

    private Sql getDocSql(String catalog, String key) {
        String ck = getKey(catalog, key);
        Sql sql =  mapforSql.get(ck);
        if (sql == null) {
            String msg = String.format("The SQL [%s] of catalog [%s] is not found in the cache.", key, catalog);
            log.error(msg);
            throw new IaisRuntimeException(msg);
        }

        return sql;
    }

    public String getSql(String catalog, String key) {
        try {
            return getSql(catalog, key, IaisCommonUtils.genNewHashMap(), false);
        } catch (IOException| TemplateException e) {
            log.error(e.getMessage(), e);
            throw new IaisRuntimeException(e);
        }
    }

    public String getSql(String catalog, String key, Map<String, Object> params) throws IOException, TemplateException {
        return getSql(catalog, key, params, true);
    }

    private String getSql(String catalog, String key, Map<String, Object> params, boolean needFreeMarkerRep) throws IOException, TemplateException {
        Sql sql = getDocSql(catalog, key);
        String sqlStat = sql.getSqlStr();
        if (isDynamicSql(sqlStat) && needFreeMarkerRep) {
            StringWriter writer = new StringWriter();
            Template temp = cfg.getTemplate(getKey(sql.getCatalog(), sql.getKey()));
            temp.process(params, writer);
            writer.flush();
            sqlStat = writer.toString();
        }
        if (!IaisCommonUtils.isEmpty(dbNameMap) && StringUtil.isNotEmpty(sqlStat)) {
            for (Map.Entry<String, String> ent : dbNameMap.entrySet()) {
                sqlStat = sqlStat.replace(ent.getKey() + ".", ent.getValue() + ".");
            }
        }
        return sqlStat;
    }

    private boolean isDynamicSql(String rawSqlStat) {
        return !StringUtil.isEmpty(rawSqlStat)
                && (rawSqlStat.contains("<#") && rawSqlStat.contains("</#")
                || rawSqlStat.contains("${"));
    }

    private String getKey(String catalog, String key) {
        return catalog + ".-salt-." + key;
    }

    private String getCacheKey(String catalog, String key) {
        return catalog + ".-salt-." + key;
    }

    public String getDynamicSqlStat(Sql sql, Map<String, Object> params) throws IOException, TemplateException {
        updateTemplate(sql);
        StringWriter writer = new StringWriter();
        Template temp = cfg.getTemplate(getCacheKey(sql.getCatalog(), sql.getKey()));
        temp.process(params, writer);
        writer.flush();
        return writer.toString();
    }

    private synchronized void updateTemplate(Sql sql) {
        if (!StringUtil.getBoolean(sql.getCached())) {
            String ck = getCacheKey(sql.getCatalog(), sql.getKey());
            StringTemplateLoader loader = (StringTemplateLoader) cfg.getTemplateLoader();
            if (loader.findTemplateSource(ck) == null) {
                loader.putTemplate(ck, sql.getSqlStr());
            }
        }
    }

    private SqlMap() {
        mapforSql = IaisCommonUtils.genNewHashMap();
    }
}
