/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;
import sop.webflow.rt.api.BaseProcessClass;

public class INTRANET___MohInspecSendRectifiToUser___1 extends BaseProcessClass {

	private static final long serialVersionUID = -1545297203904136507L;
	private static final String DELEGATOR ="inspectionSendRecDelegator";

	public void mohInspecSendRectifiToUserStart_OnStepProcess_0() throws Exception {
	// 		MohInspecSendRectifiToUserStart->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "mohInspecSendRectifiToUserStart", this);
	}

	public void mohInspecSendRectifiToUserPre_OnStepProcess_0() throws Exception {
	// 		MohInspecSendRectifiToUserPre->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "mohInspecSendRectifiToUserPre", this);
	}

}
