/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;
import sop.webflow.rt.api.BaseProcessClass;

public class INTRANET___MohRequestForInformation___1 extends BaseProcessClass {
	private static final String DELEGATOR ="requestForInformationDelegator";

	public void start_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "start", this); 
	// 		Start->OnStepProcess
	}

	public void preSearchLicence_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preSearchLicence", this); 
	// 		preSearchLicence->OnStepProcess
	}

	public void preSearchApplication_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preSearchApplication", this); 
	// 		preSearchApplication->OnStepProcess
	}

	public void doSearchApplication_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doSearchApplication", this); 
	// 		doSearchApplication->OnStepProcess
	}

	public void doSearchLicence_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doSearchLicence", this); 
	// 		doSearchLicence->OnStepProcess
	}

	public void doSearchLicenceAfter_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doSearchLicenceAfter", this); 
	// 		doSearchLicenceAfter->OnStepProcess
	}

	public void doSearchApplicationAfter_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doSearchApplicationAfter", this); 
	// 		doSearchApplicationAfter->OnStepProcess
	}

	public void preAppInfo_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preAppInfo", this);
	// 		preAppInfo->OnStepProcess
	}

	public void preReqForInfo_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preReqForInfo", this);
	// 		preReqForInfo->OnStepProcess
	}

	public void doReqForInfo_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doReqForInfo", this);
	// 		doReqForInfo->OnStepProcess
	}

	public void doCreateRequest_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doCreateRequest", this);
// 		doCreateRequest->OnStepProcess
	}

	public void doCancel_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doCancel", this);
// 		doCancel->OnStepProcess
	}

	public void doAccept_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doAccept", this);
// 		doAccept->OnStepProcess
	}

	public void preNewRfi_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preNewRfi", this);
// 		preNewRfi->OnStepProcess
	}

	public void preViewRfi_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preViewRfi", this);
// 		preViewRfi->OnStepProcess
	}

	public void preCancel_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preCancel", this);
// 		preCancel->OnStepProcess
	}

	public void doUpdate_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doUpdate", this);
	// 		doUpdate->OnStepProcess
	}

	public void preLicInfo_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preLicInfo", this);
	// 		preLicInfo->OnStepProcess
	}

	public void preSearch_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preSearch", this);
	// 		preSearch->OnStepProcess
	}

	public void preSearchLic_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preSearchLic", this);
	// 		preSearchLic->OnStepProcess
	}

	

}
