/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import sop.webflow.rt.api.BaseProcessClass;
import com.ecquaria.cloud.helper.EngineHelper;

public class INTRANET___MohPreferredDateRangePeriod___1 extends BaseProcessClass {
	private static final String DELEGATOR ="prefDateRangePeriodDelegator";
	
	
	public void preLoad_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preLoad", this); 
	}


	public void doCancel_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doCancel", this); 
	}


	public void preUpdateData_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preUpdateData", this); 
	}


	public void submitPrefDate_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "submitPrefDate", this); 
	}


	public void doBack_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doBack", this);
	}


	public void step1_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "startStep", this);
	}


	public void doSearch_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doSearch", this);
	}

}
