/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;
import sop.webflow.rt.api.BaseProcessClass;


public class INTERNET___MohAccessmentGuide___1 extends BaseProcessClass {
	private static final String DELEGATOR ="halpAssessmentGuideDelegator";


	public void start_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "start", this);
	}

	public void perDate_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "perDate", this);
	}

	public void newApp1_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "newApp1", this);
	}

	public void renewLic_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "renewLic", this);
	}

	public void renewLicUpdate_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "renewLicUpdate", this);
	}

	public void amendLic1_1_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "amendLic1_1", this);
	}

	public void amendLic1_2_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "amendLic1_2", this);
	}

	public void amendLic2_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "amendLic2", this);
	}

	public void amendLic3_1_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "amendLic3_1", this);
	}

	public void amendLic3_2_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "amendLic3_2", this);
	}

	public void amendLic4_1_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "amendLic4_1", this);
	}

	public void amendLic4_2_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "amendLic4_2", this);
	}

	public void ceaseLic_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "ceaseLic", this);
	}

	public void withdrawApp_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "withdrawApp", this);
	}

	public void resumeDraftApp_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "resumeDraftApp", this);
	}

	public void subDateMoh_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "subDateMoh", this);
	}

	public void updateAdminPers_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "updateAdminPers", this);
	}

	public void doWithdrawalStep_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doWithdrawalStep", this);
	}

	public void doRenewStep_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doRenewStep", this);
	}

	public void doCeasLicStep_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doCeasLicStep", this);
	}

	public void doNewAppStep_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doNewAppStep", this);
	}

	public void submitDateMohStep_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "submitDateMohStep", this);
	}

	public void doAmenfLicStep_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doAmenfLicStep", this);
	}

	public void resumeDraftAppStep_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "resumeDraftAppStep", this);
	}

	public void updateAdminPesStep_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "updateAdminPesStep", this);
	}

	public void prepareSwitch_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "prepareSwitch", this);
	}

	public void doWithdrawalSort_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doWithdrawalSort", this);
	}

	public void doWithdrawalPage_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doWithdrawalPage", this);
	}

	public void doCeasLicSort_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doCeasLicSort", this);
	}

	public void doCeasLicPage_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doCeasLicPage", this);
	}

	public void updateLicenceSort_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "updateLicenceSort", this);
	// 		updateLicenceSort->OnStepProcess
	}

	public void updateLicencePage_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "updateLicencePage", this);
	// 		updateLicencePage->OnStepProcess
	}

	public void addServicePage_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "addServicePage", this);
	// 		addServicePage->OnStepProcess
	}

	public void addServiceSort_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "addServiceSort", this);
	// 		addServiceSort->OnStepProcess
	}

	public void addRemovePersonalPage_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "addRemovePersonalPage", this);
	// 		addRemovePersonalPage->OnStepProcess
	}

	public void addRemovePersonalSort_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "addRemovePersonalSort", this);
	// 		addRemovePersonalSort->OnStepProcess
	}

	public void updateLicenceesPage_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "updateLicenceesPage", this);
	// 		updateLicenceesPage->OnStepProcess
	}

	public void updateLicenceesSort_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, " updateLicenceesSort", this);
	// 		updateLicenceesSort->OnStepProcess
	}

	public void updateContactSort_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "updateContactSort", this);
	// 		updateContactSort->OnStepProcess
	}

	public void updateContactPage_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "updateContactPage", this);
	// 		updateContactPage->OnStepProcess
	}
	

}
