
/*
 *   This file is generated by ECQ project skeleton automatically.
 *
 *   Copyright 2019-2049, Ecquaria Technologies Pte Ltd. All rights reserved.
 *
 *   No part of this material may be copied, reproduced, transmitted,
 *   stored in a retrieval system, reverse engineered, decompiled,
 *   disassembled, localised, ported, adapted, varied, modified, reused,
 *   customised or translated into any language in any form or by any means,
 *   electronic, mechanical, photocopying, recording or otherwise,
 *   without the prior written permission of Ecquaria Technologies Pte Ltd.
 */

/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;
import sop.webflow.rt.api.BaseProcessClass;

public class IAIS___OrgUserAccount___1 extends BaseProcessClass {
	private static final String DELEGATOR ="orgUserAccountDelegator";
	public void prepareData_OnStepProcess_0() throws Exception {
	// 		PrepareData->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "prepareData", this);
	}
	public void prepareSwitch_OnStepProcess_0() throws Exception {
	// 		PrepareSwitch->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "prepareSwitch", this);
	}
	public void doSearch_OnStepProcess_0() throws Exception {
	// 		doSearch->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "doSearch", this);
	}
	public void doSorting_OnStepProcess_0() throws Exception {
	// 		doSorting->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "doSorting", this);
	}
	public void doPaging_OnStepProcess_0() throws Exception {
	// 		doPaging->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "doPaging", this);
	}
	public void doDelete_OnStepProcess_0() throws Exception {
	// 		doDelete->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "doDelete", this);
	}

}
