/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;

import sop.webflow.rt.api.BaseProcessClass;

public class INTRANET___MohPremiseWorkload___1 extends BaseProcessClass {

	private static final String DELEGATOR ="premiseWorkload";
	
	public void start_OnStepProcess_0() throws Exception {
	// 		Start->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "start", this); 
	}

	public void preLoad_OnStepProcess_0() throws Exception {
	// 		PreLoad->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "preLoad", this); 
	}

	public void premiseWorkload_OnStepProcess_0() throws Exception {
	// 		PremiseWorkload->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "premiseWorkload", this); 
	}

	public void save_OnStepProcess_0() throws Exception {
	// 		Save->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "save", this); 
	}

	public void step1_OnStepProcess_0() throws Exception {
	// 		Step1->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "goToPremise", this); 
	}

}
