/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import sop.webflow.rt.api.BaseProcessClass;

import com.ecquaria.cloud.helper.EngineHelper;

public class INTRANET___MohServiceConfig___1 extends BaseProcessClass {
    private static final String DELEGATOR ="congfigSeriviceDelegator";
    public void start_OnStepProcess_0() throws Exception {
    // 		prepareAddAndListPage->OnStepProcess
        EngineHelper.delegate(DELEGATOR, "prepareAddAndListPage", this);
    }
    public void step3_OnStepProcess_0() throws Exception {
    // 		PrepareAddOrList->OnStepProcess
    	EngineHelper.delegate(DELEGATOR, "prepareAddOrList", this);
    }
    public void step1_OnStepProcess_0() throws Exception {
    // 		start->OnStepProcess
        EngineHelper.delegate(DELEGATOR, "start", this);
    }
    public void list_OnStepProcess_0() throws Exception {
    // 		PrepareList->OnStepProcess
        EngineHelper.delegate(DELEGATOR, "prepareList", this);
    }
    public void addNewService_OnStepProcess_0() throws Exception {
    // 		PrepareAddNewService->OnStepProcess
        EngineHelper.delegate(DELEGATOR, "prepareAddNewService", this);
    }
    public void saveOrUpdate_OnStepProcess_0() throws Exception {
    // 		DoCreate->OnStepProcess
        EngineHelper.delegate(DELEGATOR, "doCreate", this);
    }
    public void step6_OnStepProcess_0() throws Exception {
    // 		PrepareViewOrBack->OnStepProcess
        EngineHelper.delegate(DELEGATOR, "prepareViewOrBack", this);
    }
    public void edit_OnStepProcess_0() throws Exception {
    // 		PrepareView->OnStepProcess
        EngineHelper.delegate(DELEGATOR, "prepareView", this);
    }
    public void step5_OnStepProcess_0() throws Exception {
    // 		PrepareEditOrDelete->OnStepProcess
        EngineHelper.delegate(DELEGATOR, "prepareEditOrDelete", this);
    }
    public void editView_OnStepProcess_0() throws Exception {
    // 		PrepeareEdit->OnStepProcess
        EngineHelper.delegate(DELEGATOR, "prepeareEdit", this);
    }
    public void step8_OnStepProcess_0() throws Exception {
    // 		DoDelete->OnStepProcess

        EngineHelper.delegate(DELEGATOR, "doDelete", this);
    }
    public void step2_OnStepProcess_0() throws Exception {
    // 		DoUpdate->OnStepProcess
        EngineHelper.delegate(DELEGATOR, "doUpdate", this);
    }

}
