/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import sop.webflow.rt.api.BaseProcessClass;
import com.ecquaria.cloud.helper.EngineHelper;

public class INTERNET___MohInterInboxPremisesList___1 extends BaseProcessClass {

	private static final String DELEGATOR ="inboxMenuDelegator";
	
	public void preparePremisesList_OnStepProcess_0 () throws Exception { 
	
		EngineHelper.delegate(DELEGATOR, "preparePremisesList", this);
	}

	public void doPremisesList_OnStepProcess_0 () throws Exception { 
	
		EngineHelper.delegate(DELEGATOR, "doPremisesList", this);
	}

	public void doPremisesEdit_OnStepProcess_0 () throws Exception { 
	
		EngineHelper.delegate(DELEGATOR, "doPremisesEdit", this);
	}

	public void step1_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "start", this);
	}

	public void preparePremisesEdit_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preparePremisesEdit", this);
	}

	public void jump_OnStepProcess_0() throws Exception {
	// 		jump->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "jump", this);
	}

}
