/*
 * This file is generated by ECQ project skeleton automatically.
 *
 *   Copyright 2019-2049, Ecquaria Technologies Pte Ltd. All rights reserved.
 *
 *   No part of this material may be copied, reproduced, transmitted,
 *   stored in a retrieval system, reverse engineered, decompiled,
 *   disassembled, localised, ported, adapted, varied, modified, reused,
 *   customised or translated into any language in any form or by any means,
 *   electronic, mechanical, photocopying, recording or otherwise,
 *   without the prior written permission of Ecquaria Technologies Pte Ltd.
 */

package com.ecquaria.cloud.moh.iais.helper;

import com.ecquaria.cloud.moh.iais.dto.SearchParam;
import com.ecquaria.cloud.moh.iais.sql.SqlMapLoader;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.api.mockito.mockpolicies.Slf4jMockPolicy;
import org.powermock.core.classloader.annotations.MockPolicy;
import org.powermock.core.classloader.annotations.PowerMockIgnore;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;
import sg.gov.moh.iais.common.exception.IaisRuntimeException;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;

/**
 * SqlHelperTest
 *
 * @author Jinhua
 * @date 2019/7/22 17:07
 */
@RunWith(PowerMockRunner.class)
@MockPolicy(Slf4jMockPolicy.class)
@PrepareForTest({SqlHelper.class})
@PowerMockIgnore("javax.management.*")
public class SqlHelperTest {

    @Test(expected = IllegalStateException.class)
    public void testConstructor() throws NoSuchMethodException, IllegalAccessException,
            InvocationTargetException, InstantiationException {
        Class cls = SqlHelper.class;
        Constructor<SqlHelper> con = cls.getDeclaredConstructor(null);
        con.setAccessible(true);
        con.newInstance(null);
    }

    @Before
    public void setup() throws Exception {
        SqlMapLoader sqlMapLoader = new SqlMapLoader();
        sqlMapLoader.loadSqlMap();
    }

    @Test
    public void testGetSql() {
        SearchParam sp = new SearchParam(SqlHelperTest.class);
        SqlHelper.getQuerySql("testSqlMap2", "searchNothing2", sp);
        sp.addSortField("aaaa");
        sp.setPageSize(10);
        sp.setPageNo(1);
        sp.addFilter("as", "dd", true);
        SqlHelper.getQuerySql("testSqlMap2", "searchNothing2", sp);
    }

    @Test(expected = IaisRuntimeException.class)
    public void testGetSqlExp() {
        SearchParam sp = new SearchParam(SqlHelperTest.class);
        sp.setPageSize(10);
        SqlHelper.getQuerySql("testSqlMap2", "searchNothing2", sp);
    }
}
