/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import sop.webflow.rt.api.BaseProcessClass;
import com.ecquaria.cloud.helper.EngineHelper;

public class INTRANET___MohAOScreening___1 extends BaseProcessClass {
	
	private static final String DELEGATOR ="mohProcessingDelegator";

	public void step1_OnStepProcess_0() throws Exception {
	// 		Step1->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "start", this);
	}

	public void prepareData_OnStepProcess_0() throws Exception {
	// 		prepareData->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "prepareData", this);
	}

	public void approvalForInspection_OnStepProcess_0() throws Exception {
	// 		approvalForInspection->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "approvalForInspection", this);
	}

	public void reject_OnStepProcess_0() throws Exception {
	// 		reject->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "aoReject", this);
	}

	public void routeBackToDO_OnStepProcess_0() throws Exception {
	// 		routeBackToDO->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "routeBackToDO", this);
	}

	public void routeToHM_OnStepProcess_0() throws Exception {
	// 		routeToHM->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "routeToHM", this);
	}

}
