/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;

import sop.webflow.rt.api.BaseProcessClass;

public class INTRANET___MohBsbInspectionReportDOApproval___1 extends BaseProcessClass {
	private static final String DELEGATOR ="bsbInspectionReportDOApprovalDelegator";


	public void start_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "start", this);
	}

	public void pre_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "pre", this);
	}

	public void bindAction_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "bindAction", this);
	}

	public void handleSaveReport_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "handleSaveReport", this);
	}

	public void handleSubmit_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "handleSubmit", this);
	}

	public void rFI_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "rfi", this);
	}

	public void markAsFinal_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "markAsFinal", this);
	}

}
