/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;

import sop.webflow.rt.api.BaseProcessClass;

public class INTRANET___MohInspTeamNonWorkingDay___1 extends BaseProcessClass {
	private static final String DELEGATOR ="inspTeamNonWorkingDayDelegator";
	
	
	public void preLoad_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preLoad", this);
	}


	public void switchAction_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "switchAction", this);
	}


	public void preUpdate_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preUpdate", this);
	}


	public void updateNonWorkingDay_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "updateNonWorkingDay", this);
	}


	public void step1_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "startStep", this);
	}


	public void doSearch_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doSearch", this);
	}

}
