/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;
import sop.webflow.rt.api.BaseProcessClass;

public class INTERNET___InterInbox___1 extends BaseProcessClass {

private static final String DELEGATOR ="inboxDelegator";
	
	
	public void start_OnStepProcess_0() throws Exception {
		// 		Start->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "startStep", this);
	}
	
	public void prepareData_OnStepProcess_0() throws Exception {
	// 		PrepareData->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "prepareStep", this);
	}

	public void sortInbox_OnStepProcess_0() throws Exception {
	// 		SortInbox->OnStepProcess
	}

	public void sortApplication_OnStepProcess_0() throws Exception {
	// 		SortApplication->OnStepProcess
	}

	public void sortLicence_OnStepProcess_0() throws Exception {
	// 		SortLicence->OnStepProcess
	}

	public void searchInbox_OnStepProcess_0() throws Exception {
	// 		SearchInbox->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "searchInbox", this);
	}

	public void searchApplication_OnStepProcess_0() throws Exception {
	// 		SearchApplication->OnStepProcess
	}

	public void searchLicence_OnStepProcess_0() throws Exception {
	// 		SearchLicence->OnStepProcess
	}

	public void prepareSwitch_OnStepProcess_0() throws Exception {
	// 		PrepareSwitch->OnStepProcess
	}
	
	
}
