/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;

import com.ecquaria.cloud.helper.EngineHelper;
import sop.webflow.rt.api.BaseProcessClass;

public class EGPCLOUD___SupportDocumentDetail_MC___1 extends BaseProcessClass {

	private static final long serialVersionUID = -1766762307176777214L;

	public void prepareData_OnStepProcess_0() throws Exception {
//		SupportDocumentDetailsController.prepareData(request);
		EngineHelper.delegate("supportDocumentDetailsDelegator", "prepareData", request);
	}

	public void initLanguage_OnStepProcess_0() throws Exception {
//		SupportDocumentDetailsController.initLanguage(this);
		EngineHelper.delegate("supportDocumentDetailsDelegator", "initLanguage", this);
	}

}
