/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import sop.webflow.rt.api.BaseProcessClass;

public class INTRANET___MohBsbInspectionNCsDOReview___1 extends BaseProcessClass {

	public void start_OnStepProcess_0() throws Exception {
	// 		Start->OnStepProcess
	}

	public void init_OnStepProcess_0() throws Exception {
	// 		Init->OnStepProcess
	}

	public void pre_OnStepProcess_0() throws Exception {
	// 		Pre->OnStepProcess
	}

	public void bindAction_OnStepProcess_0() throws Exception {
	// 		BindAction->OnStepProcess
	}

	public void handleSubmit_OnStepProcess_0() throws Exception {
	// 		HandleSubmit->OnStepProcess
	}

	public void approve_OnStepProcess_0() throws Exception {
	// 		Approve->OnStepProcess
	}

	public void requestForInformation_OnStepProcess_0() throws Exception {
	// 		RequestForInformation->OnStepProcess
	}

	public void reject_OnStepProcess_0() throws Exception {
	// 		Reject->OnStepProcess
	}


}
