/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;

import sop.webflow.rt.api.BaseProcessClass;

public class INTRANET___MohBsbInspectionDO___1 extends BaseProcessClass {
	private static final String DELEGATOR ="bsbInspectionDO";

	public void start_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "start", this);
	}

	public void init_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "init", this);
	}

	public void pre_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "pre", this);
	}

	public void bindAction_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "bindAction", this);
	}

	public void preChecklist_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "preChecklist", this);
	}

	public void validateAndSaveChecklist_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "validateAndSaveChecklist", this);
	}

	public void saveInsFinding_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "saveInsFinding", this);
	}

	public void saveInsOutcome_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "saveInsOutcome", this);
	}

	public void handleSubmit_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "handleSubmit", this);
	}

	public void skip_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "skip", this);
	}

	public void changeTab_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "changeTab", this);// 		changeTab->OnStepProcess
	}

	public void saveDraft_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "saveDraft", this);// 		saveDraft->OnStepProcess
	}
}
