/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import sop.webflow.rt.api.BaseProcessClass;
import com.ecquaria.cloud.helper.EngineHelper;

public class INTERNET___InspectionFollowUpItems___1 extends BaseProcessClass {

	private static final String DELEGATOR ="followUpItemsDelegator";
	
	public void start_OnStepProcess_0() throws Exception {
	// 		Start->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "start", this);
	}

	public void init_OnStepProcess_0() throws Exception {
	// 		Init->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "init", this);
	}

	public void prepareData_OnStepProcess_0() throws Exception {
	// 		PrepareData->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "prepareData", this);
	}

	public void doPrepareData_OnStepProcess_0() throws Exception {
	// 		DoPrepareData->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "doPrepareData", this);
	}

	public void doSubmit_OnStepProcess_0() throws Exception {
	// 		DoSubmit->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "doSubmit", this);
	}

	public void prepareFollowUpItems_OnStepProcess_0() throws Exception {
	// 		PrepareFollowUpItems->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "prepareFollowUpItems", this);
	}

	public void doFollowUpItems_OnStepProcess_0() throws Exception {
	// 		DoFollowUpItems->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "doFollowUpItems", this);
	}

}
