/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;
import sop.webflow.rt.api.BaseProcessClass;

public class INTERNET___MohFeAdminUserManagement___1 extends BaseProcessClass {
	private static final String DELEGATOR ="feAdminManageDelegate";
	public void start_OnStepProcess_0() throws Exception {
	// 		Start->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "doStart", this);
	}
	public void preCreate_OnStepProcess_0() throws Exception {
	// 		PreCreate->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "preparePage", this);
	}
	public void validation_OnStepProcess_0() throws Exception {
	// 		CreateValidation->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "createValidation", this);
	}
	public void create_OnStepProcess_0() throws Exception {
	// 		Create->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "create", this);
	}
	public void edit_OnStepProcess_0() throws Exception {
		// 		Edit->OnStepProcess
			EngineHelper.delegate(DELEGATOR, "edit", this);
		}
	public void editValidation_OnStepProcess_0() throws Exception {
		// 		EditValidation->OnStepProcess
			EngineHelper.delegate(DELEGATOR, "editValidation", this);
		}
	public void page_OnStepProcess_0() throws Exception {
	// 		Page->OnStepProcess
		EngineHelper.delegate(DELEGATOR, "doPage", this);
	}

}
