/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;

import ecq.commons.helper.StringHelper;
import sop.i18n.MultiLangUtil;
import sop.webflow.rt.api.BaseProcessClass;

@SuppressWarnings("deprecation")
public class EGPCLOUD___SettingLanguage___1 extends BaseProcessClass {

	private static final long serialVersionUID = 4909642539253117347L;

	private static final String ATTR_LANGUAGE = "ATTR_LANGUAGE";

	public void step2_OnStepProcess_0() throws Exception {
		String language = request.getAttribute(ATTR_LANGUAGE)+"";
		if (!StringHelper.isEmpty(language)){
			switch (language){
				case "English":
					MultiLangUtil.setSiteLanguage("en");
					break;
				case "Simplified_Chinese":
					MultiLangUtil.setSiteLanguage("zh");
					break;
//					case "Traditional_Chinese":
//						locale=new Locale("zh", "TW");
//						break;
				default:
					MultiLangUtil.setSiteLanguage("en");
					break;
			}
		}

	}

}
