/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import sop.webflow.rt.api.BaseProcessClass;
import com.ecquaria.cloud.helper.EngineHelper;

public class INTRANET___MohAOCheckAuditDt___1 extends BaseProcessClass {
	private static final String DELEGATOR = "auditDateDelegator";

	public void start_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "start", this);
	}

	public void prepareData_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "prepareDOAndAOReviewData", this);
	}

	public void reject_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "aoRejectAuditDate", this);
	}

	public void approval_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "aoApprovalAuditDate", this);
	}

	public void doValidate_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "aoValidate", this);
	}
}
