/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import sop.webflow.rt.api.BaseProcessClass;
import com.ecquaria.egp.core.application.controller.delegator.ApprovalEndorsementViewDelegator;

public class EGOV___ApprovalEndorsementDetail___1 extends BaseProcessClass {

    public void step1_OnStepProcess_0() throws Exception {
        // 		Step1->OnStepProcess
        ApprovalEndorsementViewDelegator.init(this);
    }

	public void prepareDate_OnStepProcess_0() throws Exception {
	// 		prepareDate->OnStepProcess
        ApprovalEndorsementViewDelegator.prepareDate(this);
	}

	public void bindAction_OnStepProcess_0() throws Exception {
	// 		bindAction->OnStepProcess
        ApprovalEndorsementViewDelegator.bindAction(request);
	}

	public void validateEUpdateStatus_OnStepProcess_0() throws Exception {
	// 		validateEUpdateStatus->OnStepProcess
        ApprovalEndorsementViewDelegator.validateEUpdateStatus(this);
	}

	public void sortInternal_OnStepProcess_0() throws Exception {
	// 		SortInternal->OnStepProcess
        ApprovalEndorsementViewDelegator.sortInternalDoc(this);
	}

}
