/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import com.ecquaria.cloud.helper.EngineHelper;
import sop.webflow.rt.api.BaseProcessClass;

public class IAIS___Inter_Inbox___1 extends BaseProcessClass {


	private static final String DELEGATOR ="inboxTabDelegator";

	public void prepareData_OnStepProcess_0() throws Exception {
		EngineHelper.delegate(DELEGATOR, "doStart", this);
	}

	public void start_OnStepProcess_0() throws Exception {
		// 		start->OnStepProcess
	}

	public void doSearch_OnStepProcess_0() throws Exception {
		// 		doSearch->OnStepProcess
	}

	public void prepareSwitch_OnStepProcess_0() throws Exception {
		// 		PrepareSwitch->OnStepProcess
	}

	public void licencesData_OnStepProcess_0() throws Exception {
		// 		licencesData->OnStepProcess
	}

	public void applicationData_OnStepProcess_0() throws Exception {
		// 		applicationData->OnStepProcess
	}

}
