/**
 * Generated by SIT
 *
 * Feel free to add  methods  or comments. The content of this 
 * file will be kept as-is when committed.
 *
 * Extending this  class is not recommended , since the class-
 * name will change together with the version. Calling methods
 * from external code is not recommended as well , for similar
 * reasons.
 */
package sop.webflow.rt.java.code;
import sop.webflow.rt.api.BaseProcessClass;
import com.ecquaria.cloud.helper.EngineHelper;

public class INTRANET___DOProcessWithdrawn___1 extends BaseProcessClass {
//	private static final String DELEGATOR ="selfAuditDelegator";
	public void start_OnStepProcess_0() throws Exception {
//		EngineHelper.delegate(DELEGATOR, "start", this);
	}

	public void preData_OnStepProcess_0() throws Exception {
	// 		preData->OnStepProcess
	}

	public void doValidate_OnStepProcess_0() throws Exception {
	// 		doValidate->OnStepProcess
	}

	public void save_OnStepProcess_0() throws Exception {
	// 		save->OnStepProcess
	}

}
