/*
 *   This file is generated by ECQ project skeleton automatically.
 *
 *   Copyright 2019-2049, Ecquaria Technologies Pte Ltd. All rights reserved.
 *
 *   No part of this material may be copied, reproduced, transmitted,
 *   stored in a retrieval system, reverse engineered, decompiled,
 *   disassembled, localised, ported, adapted, varied, modified, reused,
 *   customised or translated into any language in any form or by any means,
 *   electronic, mechanical, photocopying, recording or otherwise,
 *   without the prior written permission of Ecquaria Technologies Pte Ltd.
 */

package com.ecquaria.cloud.moh.iais.dto;

import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;

/**
 * PostCodeDto
 *
 * @author suocheng
 * @date 8/23/2019
 */

public class PostCodeDto implements Serializable {
    private static final long serialVersionUID = -7599135028356374528L;

    @Getter @Setter private Integer id;
    @Getter @Setter private String rowguid;
    @Getter @Setter private String postalCode;
    @Getter @Setter private String addressType;
    @Getter @Setter private String blkHseNo;
    @Getter @Setter private String streetName;
    @Getter @Setter private String buildingName;
}
