/*
 * This file is generated by ECQ project skeleton automatically.
 *
 *   Copyright 2019-2049, Ecquaria Technologies Pte Ltd. All rights reserved.
 *
 *   No part of this material may be copied, reproduced, transmitted,
 *   stored in a retrieval system, reverse engineered, decompiled,
 *   disassembled, localised, ported, adapted, varied, modified, reused,
 *   customised or translated into any language in any form or by any means,
 *   electronic, mechanical, photocopying, recording or otherwise,
 *   without the prior written permission of Ecquaria Technologies Pte Ltd.
 */

package com.ecquaria.cloud.moh.iais.sql;

import com.ecquaria.cloud.moh.iais.helper.IaisEGPHelper;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Spy;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.api.mockito.mockpolicies.Slf4jMockPolicy;
import org.powermock.core.classloader.annotations.MockPolicy;
import org.powermock.core.classloader.annotations.PowerMockIgnore;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;
import sg.gov.moh.iais.common.constant.AppConsts;

import java.io.File;

import static org.junit.Assert.assertNotNull;

/**
 * SqlMapLoaderTest
 *
 * @author Jinhua
 * @date 2019/7/22 10:18
 */
@RunWith(PowerMockRunner.class)
@MockPolicy(Slf4jMockPolicy.class)
@PrepareForTest({SqlMapLoader.class})
@PowerMockIgnore("javax.management.*")
public class SqlMapLoaderTest {
    @Spy
    private SqlMapLoader sml = new SqlMapLoader();

    @Test
    public void testGetDir() {
        String s = SqlMapLoader.getDir();
        assertNotNull(s);
    }

    @Test
    public void testLoadSqlMapNull() throws Exception {
        File testFolder = new File(Thread.currentThread().getContextClassLoader().getResource("")
                .getPath(), "querySqlss");
        PowerMockito.whenNew(File.class).withArguments(IaisEGPHelper.getRootPath() + "WEB-INF"
                + AppConsts.FILE_SEPARATOR + "classes" + AppConsts.FILE_SEPARATOR, "querySqls")
                .thenReturn(testFolder);
        sml.loadSqlMap();
        testFolder = null;
        PowerMockito.whenNew(File.class).withArguments(IaisEGPHelper.getRootPath() + "WEB-INF"
                + AppConsts.FILE_SEPARATOR + "classes" + AppConsts.FILE_SEPARATOR, "querySqls")
                .thenReturn(testFolder);
        sml.loadSqlMap();
        assertNotNull(sml);
    }

    @Test
    public void testLoadSqlMap() throws Exception {
        sml.loadSqlMap();
        assertNotNull(sml);
    }
}
