FROM tomcat:9.0.29-jdk8-adoptopenjdk-hotspot

COPY target/web.war /usr/local/tomcat/webapps/web.war

COPY docker/setenv.sh /usr/local/tomcat/bin/setenv.sh
COPY docker/server.xml /usr/local/tomcat/conf/server.xml
RUN chmod +x /usr/local/tomcat/bin/setenv.sh

CMD ["/usr/local/tomcat/bin/catalina.sh", "run"]



